"""empty message

Revision ID: ea0854580ba2
Revises: 1d4d808149b6
Create Date: 2018-05-26 09:40:31.395911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0854580ba2'
down_revision = '1d4d808149b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'status')
    # ### end Alembic commands ###
